config/routes.rb
LogalingServer::Application.routes.draw do
  get "search", :as => :search, :controller => 'search', :action => :index

  %w(license about explore).each do |page_name|
    get page_name, to: "pages##{page_name}", as: page_name
  end

  resources :github_projects,
            :path => 'github',
            :constraints => {:id => %r{[^/]+/[^/]+}},
            :only => [:show, :new, :create] do
    resources :glossaries,
              :constraints => {:id => %r{[^-]+-[^-]+}},
              :only => :show
  end

  resources :users, :only => [:create] do
    resources :github_project_memberships,
      :only => [:new, :create, :destroy]
    resources :user_glossaries,
      :path => 'glossaries',
      :constraints => {:id => %r{[^/]+/[^/]+}},
      :only => [:new, :create, :show, :destroy],
      :as => :glossaries do
        resources :terms,
          :constraints => {:id => %r{[^/]+}, :glossary_id => %r{[^/]+/[^/]+}}
    end
    resources :user_configs,
      :path => 'configs',
      :as => :configs
  end

  resources :external_glossaries,
            :path => 'glossaries',
            :constraints => {:id => %r{[^/]+/[^/]+}},
            :only => :show,
            :as => :glossaries

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure'
  match '/signup' => 'users#new', as: :signup
  match '/signin' => 'sessions#new', as: :signin
  match "/signout" => "sessions#destroy", :as => :signout
  match "/dashboard" => "dashboard#show", :as => :dashboard

  root :to => 'top#index'
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @projects = GithubProject.all
  end
end

app/views/top/index.html.haml
- @title = "HOME"
.catch
  .container
    %h1
      Use logaling and translate the world.
    %p
      = link_to 'Learn more »', about_path, :class => 'learnMore'

.container
  .row
    %section.span4.addNewProject
      %h1
        GitHubプロジェクトを登録する
      %p
        = link_to 'プロジェクトを登録する', new_github_project_path, :class => 'addNewProjectBtn'
    %section.span8.projectsList
      %h1
        =image_tag 'homeProjectsUsingLogaling.png', :alt => 'Projects using logaling'
      %ul
        - @projects.each do |project|
          %li
            = link_to project.full_name, project