config/routes.rb
LogalingServer::Application.routes.draw do
  get "search", :as => :search, :controller => 'search', :action => :index

  %w(license about explore).each do |page_name|
    get page_name, to: "pages##{page_name}", as: page_name
  end

  resources :github_projects,
            :path => 'github',
            :constraints => {:id => %r{[^/]+/[^/]+}},
            :only => [:show, :new, :create] do
    resources :glossaries,
              :constraints => {:id => %r{[^-]+-[^-]+}},
              :only => :show
  end

  resources :users, :only => [:create] do
    resources :github_project_memberships,
      :only => [:new, :create, :destroy]
    resources :user_glossaries,
      :path => 'glossaries',
      :constraints => {:id => %r{[^/]+/[^/]+}},
      :only => [:new, :create, :show, :destroy],
      :as => :glossaries do
        resources :terms,
          :constraints => {:id => %r{[^/]+}, :glossary_id => %r{[^/]+/[^/]+}}
    end
    resources :user_configs,
      :path => 'configs',
      :as => :configs
  end

  resources :external_glossaries,
            :path => 'glossaries',
            :constraints => {:id => %r{[^/]+/[^/]+}},
            :only => :show,
            :as => :glossaries

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure'
  match '/signup' => 'users#new', as: :signup
  match '/signin' => 'sessions#new', as: :signin
  match "/signout" => "sessions#destroy", :as => :signout
  match "/dashboard" => "dashboard#show", :as => :dashboard

  root :to => 'top#index'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate!

  def show
    @user_config = current_user.user_config || UserConfig.new
    @user_glossaries = current_user.user_glossaries
    @github_projects = current_user.github_projects
  end
end

app/views/dashboard/show.html.haml
- @title = "マイページ"
.container
  %h1
    = @title
  %h2
    わたしの用語集
  %p
    =link_to "新しい用語集をつくる", new_user_glossary_path(:user_id => current_user), :class => 'addNewProjectBtn'
  %h3
    用語集一覧
  %ul.glossariesList
    - @user_glossaries.each do |user_glossary|
      %li
        = link_to user_glossary.link_text, user_glossary_path(current_user, user_glossary)
        %span.btn-group.actions
          %label{ :for => "commit_#{user_glossary.id}", :class => "btn btn-mini" }
            = @user_config.mark_for(user_glossary)
            = form_for @user_config, url: @user_config.submit_path_for(current_user), :html => {:style => "margin:0;"} do |f|
              = f.hidden_field :glossary_name, value: user_glossary.glossary_name
              = f.hidden_field :source_language, value: user_glossary.source_language
              = f.hidden_field :target_language, value: user_glossary.target_language
              = f.submit '', :class => 'hidden', :id => "commit_#{user_glossary.id}"
          = link_to raw("<i class=icon-file></i>"), new_user_glossary_path(current_user, original_user_glossary_id: user_glossary.id), { :class => 'btn btn-mini', :title => 'この用語集をベースに新しい用語集を作成する' }
          = link_to raw("<i class=icon-trash></i>"), user_glossary_path(current_user, user_glossary), method: :delete, :class => 'btn btn-mini', :title => '用語集を削除する', data: { confirm: '用語集を削除します。よろしいですか?' }

  %h2
    参加しているGitHubプロジェクトの管理
  %p
    =link_to 'プロジェクトを登録する', new_user_github_project_membership_path(:user_id => current_user), :class => 'addNewProjectBtn'
  %h3
    プロジェクト一覧
  %ul.projectsList
    - @github_projects.each_with_index do |github_project, i|
      %li
        = github_project.full_name
        %span.btn-group.actions
          = link_to raw("<i class=icon-trash></i>"), user_github_project_membership_path(current_user, github_project.memberships.of(current_user).first), method: :delete, :class => 'btn btn-mini', :title => 'プロジェクトへの参加を取り消す', data: { confirm: 'プロジェクトへの参加を取り消します。よろしいですか?' }
        %ul.glossariesList
          - github_project.glossaries.each_with_index do |glossary, j|
            %li
              - bilingual_pair = [glossary.source_language, glossary.target_language].join('-')
              = link_to "#{glossary.source_language} #{glossary.target_language}", github_project_glossary_path(:id => bilingual_pair, :github_project_id => github_project)
              %span.btn-group.actions
                %label{ :for => "commit_github_project_glossary_#{i}#{j}", :class => "btn btn-mini" }
                  = @user_config.mark_for(glossary)
              = form_for @user_config, url: @user_config.submit_path_for(current_user), :html => { :style => "margin:0;" } do |f|
                = f.hidden_field :glossary_name, value: glossary.name
                = f.hidden_field :source_language, value: glossary.source_language
                = f.hidden_field :target_language, value: glossary.target_language
                = f.submit '', :class => 'hidden', :id => "commit_github_project_glossary_#{i}#{j}"