config/routes.rb
LogalingServer::Application.routes.draw do
  get "search", :as => :search, :controller => 'search', :action => :index

  %w(license about explore).each do |page_name|
    get page_name, to: "pages##{page_name}", as: page_name
  end

  resources :github_projects,
            :path => 'github',
            :constraints => {:id => %r{[^/]+/[^/]+}},
            :only => [:show, :new, :create] do
    resources :glossaries,
              :constraints => {:id => %r{[^-]+-[^-]+}},
              :only => :show
  end

  resources :users, :only => [:create] do
    resources :github_project_memberships,
      :only => [:new, :create, :destroy]
    resources :user_glossaries,
      :path => 'glossaries',
      :constraints => {:id => %r{[^/]+/[^/]+}},
      :only => [:new, :create, :show, :destroy],
      :as => :glossaries do
        resources :terms,
          :constraints => {:id => %r{[^/]+}, :glossary_id => %r{[^/]+/[^/]+}}
    end
    resources :user_configs,
      :path => 'configs',
      :as => :configs
  end

  resources :external_glossaries,
            :path => 'glossaries',
            :constraints => {:id => %r{[^/]+/[^/]+}},
            :only => :show,
            :as => :glossaries

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure'
  match '/signup' => 'users#new', as: :signup
  match '/signin' => 'sessions#new', as: :signin
  match "/signout" => "sessions#destroy", :as => :signout
  match "/dashboard" => "dashboard#show", :as => :dashboard

  root :to => 'top#index'
end

app/views/shared/_term.html.haml
.term
  .row
    .span9
      %span.label<>
        = term.source_language
      = render_sinpped(term.snipped_source_term)
      %span.label<>
        = term.target_language
      = term.target_term
      - unless term.note.empty?
        %span.label<>
          = "note"
        = term.note
    .span2.property
      - if term.github_project?
        %p.githubProject
          = link_to_glossary_with(term)
      - elsif term.user_glossary?
        %p.logalingProject
          = link_to_glossary_with(term)
          - if signed_in?
            - user_glossary = UserGlossary.find_by_term_and_user(term, current_user)
            - if user_glossary
              %p.btn-group.actions
                = link_to raw("<i class=icon-pencil></i>"), edit_user_glossary_term_path(current_user, user_glossary, term.id), :class => 'btn btn-mini', :title => '用語を編集する'
                = link_to raw("<i class=icon-trash></i>"), user_glossary_term_path(current_user, user_glossary, term.id), method: :delete, :class => 'btn btn-mini', :title => '用語を削除する', data: { confirm: '用語を削除します。よろしいですか?' }
      - else
        %p
          %i.icon-folder-open
          = term.glossary_name